name: Databricks Deploy
on:
  push:
    branches:
      - main
jobs:
  Databricks-Deploy-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: test
        uses: xwskx/github-action-test@main
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install Python libaries
        run: find -type f
