name: Databricks Deploy
on:
  push:
    branches:
      - master
jobs:
  Databricks-Deploy-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install Python libaries
        run: ls -la
